- name: Add Docker on Centos
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
  when: ansible_facts['os_family'] == "RedHat"

- name: Add Docker on Ubuntu
  become: true
  block:
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repo
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
  when: ansible_facts['os_family'] == "Debian" 

- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{  item  }}"
    state: present
  loop: "{{  packages  }}"

- name: Start and enable the Docker daemon
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
