- name: Add user
  become: true
  ansible.builtin.user:
    name: "{{  user  }}"
    home: "{{  home_dir  }}"
    shell: "{{  shell  }}"
    
- name: Add root
  become: true
  ansible.builtin.user:
    name: "{{  user  }}"
    groups: "{{  group  }}"
  tags: root
