- name: Add user
  become: true
  ansible.builtin.user:
    name: "{{  item.name  }}"
    home: "{{  item.home_dir  }}"
    shell: "{{  item.shell  }}"
  loop: "{{  users  }}"
    
- name: Add root
  become: true
  ansible.builtin.user:
    name: "{{  item.name  }}"
    groups: "{{  sudo_group  }}"
  loop: "{{  users  }}"
  tags: root
