ansible_user: vagrant
ansible_ssh_private_key_file: ~/.ssh/id_rsa
packages: 
  - git
  - python3
  - docker-ce
  - docker-ce-cli
  - containerd.io
user: hw20
shell: /bin/sh
home_dir: /opt/"{{  user  }}"
repo: https://github.com/Gritskov-Vitaliy/Test_repo.git
template_src: zone.j2
template_dest: tmp/HW20_FILE_INFO
copy_dest: tmp/
