- name: Copy file
  become: true
  ansible.builtin.copy:
    src: "{{  item.file  }}"
    dest: "{{  item.dest  }}"
  loop: "{{  copy  }}"

- name: Add permissions
  become: true
  ansible.builtin.file:
    path: "{{  item.0.dest  }}"
    owner: "{{  item.1.name  }}"
    mode: "{{ item.0.mode  }}"
  loop: "{{  copy|zip(users)|list  }}"
  tags: permissions
