Vagrant.configure("2") do |config|
  config.vm.define "S1" do |s1|
    s1.vm.box = "ubuntu/focal64"
    s1.vm.network "private_network", ip: "192.168.33.13"
   end
   config.vm.define "S2" do |s2|
    s2.vm.box = "centos/8"
    s2.vm.network "private_network", ip: "192.168.33.14"
   end

   config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("D:/Vagrant/id_rsa.pub").first.strip  #Path to SSH key from Windows
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end
end
