---
- name: Restart docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
