- name: Create template files
  become: true
  ansible.builtin.template:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{  item.owner  }}"
    mode: "{{ item.mode }}"
  loop: "{{  template  }}"
