Vagrant.configure("2") do |config|
  config.vm.define "VM1" do |vm1|
    vm1.vm.box = "ubuntu/groovy64"
    vm1.vm.network "private_network", ip: "192.168.33.10"
   end
   config.vm.define "VM2" do |vm2|
    vm2.vm.box = "ubuntu/groovy64"
    vm2.vm.network "private_network", ip: "192.168.33.11"
   end
   config.vm.define "VM3" do |vm3|
    vm3.vm.box = "centos/8"
    vm3.vm.network "private_network", ip: "192.168.33.12"
   end
   
   config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("D:/Vagrant/id_rsa.pub").first.strip  #Path to SSH key from Windows
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end
end
